language: generic
os: linux

branches:
  only:
  - master

services:
- docker

env:
  global:
  - NJOBS="2"
  - CONTRIB="analysis"
  - OPAMYES=yes
  jobs:
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.11"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.12"

install:
- docker pull ${DOCKERIMAGE}
- docker tag  ${DOCKERIMAGE} ci:current
- docker run  --env=OPAMYES --init -id --name=CI -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB} -w /home/coq/${CONTRIB} ci:current
- docker exec CI /bin/bash --login -c "opam update -y"
- docker exec CI /bin/bash --login -c "opam pin add -n -y -k path coq-mathcomp-${CONTRIB}.dev ."
- docker exec CI /bin/bash --login -c "opam install --deps-only coq-mathcomp-${CONTRIB}"

script:
- docker exec CI /bin/bash --login -c "opam install -vvv coq-mathcomp-${CONTRIB}"
