name: Cachix
on:
  push:
jobs:
  cachix:
    name: Cachix branch
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        # Name of a cachix cache to push and pull/substitute
        name:  math-comp
        # Authentication token for Cachix, needed only for private cache access
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: actions/checkout@v2
    - run: nix-build
    # - run: export CACHIX_SIGNING_KEY=${{ secrets.CACHIX_SIGNING_KEY }} cachix push math-comp result
